# Generated by Django 4.0.5 on 2022-06-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Magura', 'Magura'), ('Sylhet', 'Sylhet'), ('Khulna', 'Khulna')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('pimage', models.ImageField(blank=True, upload_to='images')),
                ('rdoc', models.FileField(blank=True, upload_to='rdocs')),
            ],
        ),
    ]
